title: PGH TALONG
description: Task Automation for Laboratory Orders and Needs Generator
theme: minima
url: "https://pghtalong.github.io"
baseurl: ""  # leave blank unless your site is in a subfolder
